baseURL = 'https://dao.like.co/'
title = 'LikeCoin DAO'
languageCode = 'en-US'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true

[params]
description = "The official website for LikeCoin DAO, the decentralized protocol powering 3ook.com - a decentralized bookstore."
images = ["/assets/likecoin-banner.png"]
whitepaper = "https://3ook.com/store/0x3ddc416c403449bc2a9ae873bff0b687993cd662"

[params.social]
twitter = "likecoin"

[params.like]
uniswap = "https://app.uniswap.org/explore/tokens/base/0x1ee5dd1794c28f559f94d2cc642bae62dc3be5cf"
coingecko = "https://www.coingecko.com/en/coins/likecoin"
coinmarketcap = "https://coinmarketcap.com/currencies/likecoin/"

[params.get_involved]
github = "https://github.com/likecoin"
governance = "https://snapshot.box/#/s:likerland.eth"
docs = "https://docs.3ook.com"

[params.social_media]
youtube = "https://youtube.com/likecoin"
x = "https://x.com/likecoin"
reddit = "https://reddit.com/r/likecoin"
github = "https://github.com/likecoin"
substack = "https://likecoin.substack.com"
threads = "https://threads.com/@3ookcom"
instagram = "https://instagram.com/3ookcom"
facebook = "https://facebook.com/likecoin"
mail = "mailto:cs@3ook.com"
website = "https://like.co"

[params.chain]
token_contract = "https://basescan.org/token/0x1EE5DD1794C28F559f94d2cc642BaE62dC3be5cf"
deposit_contract = "https://basescan.org/token/0xE55C2b91E688BE70e5BbcEdE3792d723b4766e2B"
staking_contract = "https://basescan.org/address/0x4506ac2dd1e9a470d92a3d1656e1a99c676e1c8e"
staking_nft_contract = "https://opensea.io/collection/likestakeposition"
debook_contract = "https://basescan.org/address/0xfb5cbb1973a092E6C77af02EA1E74B14870AbeC5"
multisig_treasury = "https://app.safe.global/home?safe=base:0x3aFaEA57802E0b8380d6461a62efbd5346752e83"
tech_subdao_multisig = "https://app.safe.global/home?safe=base:0x07f7355F73af2Ea47CDf0DE97853776bd833D67b"

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    contentDir = 'content'
    weight = 1

  [languages.zh]
    languageCode = 'zh-Hant'
    languageName = '繁體中文'
    contentDir = 'content'
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[services]
  [services.googleAnalytics]
    id = 'G-G9WM2V5EW6'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

[imaging]
  resampleFilter = "CatmullRom"
  quality = 85
  anchor = "center"


[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
